"""Publish drafts: GitHub Issue (primary), optional markdown, optional LinkedIn."""

from __future__ import annotations

import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import httpx

from .config import AppConfig
from .github_client import GitHubClient, GitHubError
from .models import GeneratedDraft, ScoredEvent
from .state import format_dt

log = logging.getLogger("github_to_linkedin.output")


class OutputError(RuntimeError):
    pass


def publish_draft(
    draft: GeneratedDraft,
    cfg: AppConfig,
    github: GitHubClient,
    *,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Create the GitHub Issue (and optional side outputs). Returns result metadata."""
    result: dict[str, Any] = {"issue_url": None, "markdown_path": None, "linkedin_id": None}
    title = issue_title(draft)
    body = issue_body(draft, cfg)

    if dry_run:
        log.info("[dry-run] Would create issue: %s", title)
        log.info("[dry-run] Post (%s words):\n%s", draft.word_count, draft.post_text)
        if cfg.output.write_markdown:
            log.info("[dry-run] Would write markdown under %s", cfg.output.markdown_dir)
        if cfg.linkedin.auto_post:
            log.info("[dry-run] Would auto-post to LinkedIn (flag is enabled)")
        return result

    if cfg.output.create_github_issue:
        repo = _output_repo(cfg)
        try:
            issue = github.create_issue(
                repo,
                title=title,
                body=body,
                labels=list(cfg.output.issue_labels),
            )
        except GitHubError as exc:
            raise OutputError(f"Failed to create GitHub issue in {repo}: {exc}") from exc
        url = issue.get("html_url")
        result["issue_url"] = url
        log.info("Created issue %s", url)
    else:
        log.info("create_github_issue is false; skipped issue")

    if cfg.output.write_markdown:
        path = write_markdown(draft, cfg, body)
        result["markdown_path"] = str(path)

    if cfg.linkedin.auto_post:
        post_id = post_to_linkedin(draft.post_text, cfg)
        result["linkedin_id"] = post_id
    else:
        log.info("LinkedIn auto-post disabled (default). Draft only.")

    return result


def issue_title(draft: GeneratedDraft) -> str:
    day = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    score = int(round(draft.score))
    return f"LinkedIn Draft – {day} – score {score:02d}"


def issue_body(draft: GeneratedDraft, cfg: AppConfig) -> str:
    lead = draft.candidate.lead
    confidence = "high confidence" if draft.high_confidence else "above draft threshold"
    sources = [_source_block(item) for item in draft.candidate.all_events]
    breakdown_rows = "\n".join(
        f"| {name} | {value:+.1f} |" for name, value in lead.breakdown.as_rows()
    )
    feature_rows = _feature_table(lead)
    posted_checkbox = (
        "- [x] Auto-posted to LinkedIn (see run logs for URN)"
        if cfg.linkedin.auto_post
        else "- [ ] Posted to LinkedIn"
    )
    return f"""## Draft post

{draft.post_text}

---

## Metadata

| | |
| --- | --- |
| Score | **{draft.score:.1f}** / 100 ({confidence}) |
| Draft threshold | {cfg.scoring.draft_threshold:.0f} |
| High-confidence threshold | {cfg.scoring.high_confidence_threshold:.0f} |
| Provider | `{draft.provider}` |
| Model | `{draft.model}` |
| Word count | {draft.word_count} |
| Lead event | `{lead.event.event_type}` · {lead.event.repo_full_name} |

### Why this scored

{draft.reasoning}

{posted_checkbox}
- [ ] Edited before posting

## Source events

{chr(10).join(sources)}

## Feature breakdown

| Feature | Value |
| --- | --- |
{feature_rows}

## Score components

| Component | Points |
| --- | --- |
{breakdown_rows}
| **raw total** | **{lead.breakdown.total:.1f}** |
| **clamped score** | **{lead.breakdown.clamped:.1f}** |

---
<sub>Generated by github-to-linkedin-drafts. Scoring is deterministic; the model only wrote the prose.</sub>
"""


def write_markdown(draft: GeneratedDraft, cfg: AppConfig, body: str) -> Path:
    directory = Path(cfg.output.markdown_dir)
    directory.mkdir(parents=True, exist_ok=True)
    day = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    slug = draft.candidate.lead.event.repo_full_name.replace("/", "-")
    path = directory / f"{day}-{slug}-score-{int(round(draft.score))}.md"
    header = f"# {issue_title(draft)}\n\n"
    path.write_text(header + body, encoding="utf-8")
    log.info("Wrote markdown draft to %s", path)
    return path


def post_to_linkedin(text: str, cfg: AppConfig) -> str:
    token = os.environ.get("LINKEDIN_ACCESS_TOKEN", "").strip()
    if not token:
        raise OutputError(
            "linkedin.auto_post is true but LINKEDIN_ACCESS_TOKEN is not set."
        )
    person_urn = cfg.linkedin.person_urn.strip() or _linkedin_person_urn(token)
    payload = {
        "author": person_urn,
        "lifecycleState": "PUBLISHED",
        "specificContent": {
            "com.linkedin.ugc.ShareContent": {
                "shareCommentary": {"text": text},
                "shareMediaCategory": "NONE",
            }
        },
        "visibility": {"com.linkedin.ugc.MemberNetworkVisibility": "PUBLIC"},
    }
    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(
                "https://api.linkedin.com/v2/ugcPosts",
                headers={
                    "Authorization": f"Bearer {token}",
                    "Content-Type": "application/json",
                    "X-Restli-Protocol-Version": "2.0.0",
                },
                json=payload,
            )
    except httpx.HTTPError as exc:
        raise OutputError(f"LinkedIn request failed: {exc}") from exc
    if response.status_code >= 400:
        raise OutputError(
            f"LinkedIn UGC API {response.status_code}: {response.text[:800]}"
        )
    post_id = response.headers.get("x-restli-id") or response.headers.get("x-linkedin-id")
    if not post_id:
        try:
            post_id = str(response.json().get("id") or "unknown")
        except Exception:
            post_id = "unknown"
    log.info("Posted to LinkedIn (%s)", post_id)
    return post_id


def _linkedin_person_urn(token: str) -> str:
    try:
        with httpx.Client(timeout=20.0) as client:
            response = client.get(
                "https://api.linkedin.com/v2/userinfo",
                headers={"Authorization": f"Bearer {token}"},
            )
    except httpx.HTTPError as exc:
        raise OutputError(f"LinkedIn userinfo failed: {exc}") from exc
    if response.status_code >= 400:
        raise OutputError(
            "Could not resolve LinkedIn person URN. Set linkedin.person_urn "
            f"or LINKEDIN_PERSON_URN. userinfo {response.status_code}: {response.text[:300]}"
        )
    data = response.json()
    sub = data.get("sub")
    if not sub:
        raise OutputError("LinkedIn userinfo did not include 'sub'")
    return f"urn:li:person:{sub}"


def _output_repo(cfg: AppConfig) -> str:
    repo = cfg.github.output_repo.strip() or os.environ.get("GITHUB_REPOSITORY", "").strip()
    if not repo:
        raise OutputError(
            "Cannot create an issue: set github.output_repo or GITHUB_REPOSITORY."
        )
    return repo


def _source_block(item: ScoredEvent) -> str:
    event = item.event
    when = format_dt(event.created_at) or ""
    url = event.html_url or ""
    return (
        f"### {event.event_type} — {event.repo_full_name} (score {item.score:.1f})\n"
        f"- **Title:** {event.title}\n"
        f"- **When:** {when}\n"
        f"- **URL:** {url}\n"
        f"- **Diff:** +{event.additions} / -{event.deletions} · {event.files_changed} files\n"
    )


def _feature_table(item: ScoredEvent) -> str:
    f = item.features
    rows = [
        ("event_type", f.event_type),
        ("lines_changed", f.lines_changed),
        ("files_changed", f.files_changed),
        ("conventional_type", f.conventional_type or "—"),
        ("is_breaking", f.is_breaking),
        ("positive_keywords", ", ".join(f.positive_keywords) or "—"),
        ("negative_keywords", ", ".join(f.negative_keywords) or "—"),
        ("title_length", f.title_length),
        ("body_length", f.body_length),
        ("title_quality", f.title_quality),
        ("body_quality", f.body_quality),
        ("repo_stars", f.repo_stars),
        ("repo_forks", f.repo_forks),
        ("hours_since_last_high_score", _fmt_hours(f.hours_since_last_high_score)),
        ("is_default_branch", f.is_default_branch),
        ("commit_count", f.commit_count),
    ]
    return "\n".join(f"| `{k}` | {v} |" for k, v in rows)


def _fmt_hours(value: float | None) -> str:
    if value is None:
        return "—"
    return f"{value:.1f}h"
